version: '3'
services:
  my-back:
    image: mcrash01/myapp:v1
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=your_database_url_here

  my-front:
    image: mcrash01/myapp_front:v1
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=http://my-back:8080
